line-length = 150  # Set max line length (default is 88, like Black)

[lint]
select = ["E", "F", "I"]  # E = Pycodestyle errors, F = Pyflakes, I = isort
fixable = ["ALL"]  # Allow auto-fixing of all errors
# Exclude specific directories (e.g., virtualenv, migrations, etc.)
exclude = ["venv", "tests", "migrations"]

[lint.isort]
force-sort-within-sections = true
